// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3SJiV9u5mw-giOHaDXD0xKWxwJGjrzx4',
    appId: '1:786564772089:web:2237f2e461a3e7877e3228',
    messagingSenderId: '786564772089',
    projectId: 'skilltime-pro',
    authDomain: 'skilltime-pro.firebaseapp.com',
    storageBucket: 'skilltime-pro.firebasestorage.app',
    measurementId: 'G-DNSWBF5LHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuuyQRwsqCFYCcjfOFGpNBKczSI4HzZA',
    appId: '1:786564772089:android:49bef6c9123f2f837e3228',
    messagingSenderId: '786564772089',
    projectId: 'skilltime-pro',
    storageBucket: 'skilltime-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Q0HrlN8BxX4fNvpCiEyTFWTHe-A6gfE',
    appId: '1:786564772089:ios:6ebd57afa1259da77e3228',
    messagingSenderId: '786564772089',
    projectId: 'skilltime-pro',
    storageBucket: 'skilltime-pro.firebasestorage.app',
    iosBundleId: 'com.skilltime.skillTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Q0HrlN8BxX4fNvpCiEyTFWTHe-A6gfE',
    appId: '1:786564772089:ios:6ebd57afa1259da77e3228',
    messagingSenderId: '786564772089',
    projectId: 'skilltime-pro',
    storageBucket: 'skilltime-pro.firebasestorage.app',
    iosBundleId: 'com.skilltime.skillTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3SJiV9u5mw-giOHaDXD0xKWxwJGjrzx4',
    appId: '1:786564772089:web:b831e6d155cee0327e3228',
    messagingSenderId: '786564772089',
    projectId: 'skilltime-pro',
    authDomain: 'skilltime-pro.firebaseapp.com',
    storageBucket: 'skilltime-pro.firebasestorage.app',
    measurementId: 'G-GL0HR9F546',
  );
}
